version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:20.18.0
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run test-server:build
      - run: npm run test-proxy:build
      - run: npm run test-server:start
      - run: npm test
      - run: npm run test-server:stop

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
